name: ArgoCD

on:
  push:
    branches:
      - prod
    paths:
      - "environments/**"

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      dev: ${{ steps.filter.outputs.dev }}
      prod: ${{ steps.filter.outputs.prod }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          dev:
            - 'environments/dev/**'
          prod:
            - 'environments/sta/**'

  # JOB to deploy dev
  dev:
    container:
      image: bitnami/kubectl:1.24
    needs: changes
    if: ${{ needs.changes.outputs.dev == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          kubectl apply -k roava-dev/

  # JOB to deploy prod
  prod:
    container:
        image: bitnami/kubectl:1.24
    needs: changes
    if: ${{ needs.changes.outputs.prod == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          kubectl apply -k roava-prod/

