name: Sync Repos
on:
  push:
    branches:
      - dev # change
  # for manual deployments
  workflow_dispatch: 
    inputs:
      tag:
        description: 'Specify tag to create'
        required: true
        type: string
      
jobs:
  Tag:
    name: "Create Tag"
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: ./deploy-java # change

      - name: Set tag
        run: |
          cd ./deploy-java
          set -eux
          git fetch --unshallow
          git describe --abbrev=0 --match "v*" --tags
          CURTAG=`git describe --match "v*" --tags | sort -u | cut -d"-" -f1`;
          echo "Current tag: $CURTAG"
          CURTAG="${CURTAG/v/}"
          
          IFS='.' read -a vers <<< "$CURTAG"
          
          MAJ=${vers[0]}
          MIN=${vers[1]}

          ((MIN+=1))

          echo "TAG=v$MAJ.$MIN" >> $GITHUB_ENV
          echo "Current: v$MAJ.$MIN"

      - name: Create tag in source repo
        run: |
          cd deploy-java # change
          git config user.email "test@gmail.com" # change
          git config user.name "praise" # change
          echo "Current: $TAG"
          echo "Create Tag and push"
          git tag -a $TAG -m "test tag"
          git push -f origin $TAG
          
  Sync:
    name: "Sync Repos"
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    env:
      TAG: ${{ inputs.tag }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: ./deploy-java
          ref: $TAG # change

      - name: Checkout dest repo
        uses: actions/checkout@v3
        with:
          repository: Anefu/php-todo # change
          ssh-key: ${{ secrets.DEST_SSH_KEY }} # change
          path: ./php-todo # change
          ref: main # change

      - name: Sync directories
        run: |
          cd deploy-java # change
          echo "Fetching Tags"
          git fetch --tags
          echo "Checkout recent tag"
          git checkout $TAG
          rsync -av --exclude='**/.git*' --exclude='**/*.yml' ./ ../php-todo/ # change, specify paths to exclude
      
      - name: Create commit and push
        run: |
          cd ./php-todo # change
          git config user.email "test@gmail.com" # change
          git config user.name "praise" # change
          echo "Add changes, if any"
          git add .
          echo "Commit changes if any or exit"
          git commit -m "test sync" || exit 0
          git push origin main
