name: Sync Repos
on:
  push:
    branches:
      - dev

jobs:
  Sync:
    name: "Sync Repos"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: ./deploy-java

      - name: Checkout dest repo
        uses: actions/checkout@v3
        with:
          repository: Anefu/php-todo
          ssh-key: ${{ secrets.DEST_SSH_KEY }}
          path: ./php-todo
          ref: main

      - name: Create tag in source repo
        run: |
          cd deploy-java
          export TAG=$(( $RANDOM % 10 ))
          git config user.email "test@gmail.com"
          git config user.name "praise"
          echo "Create Tag and push"
          git tag -a $TAG -m "test tag"
          git push origin $TAG

      - name: Sync directories
        run: |
          cd deploy-java
          echo "Fetching Tags"
          git fetch --tags
          echo "Checkout recent tag"
          git checkout $TAG
          rsync -av --exclude='**/.git*' --exclude='**/*.yml' ./ ../php-todo/
      
      - name: Create commit and push
        run: |
          cd ./php-todo
          git config user.email "test@gmail.com"
          git config user.name "praise"
          echo "Add changes, if any"
          git add .
          "Commit changes if any or exit"
          git commit -m "test sync" || exit 0
          git push origin main
