name: Sync Repos
on:
  push:
    branches:
      - dev

jobs:
  Sync:
    name: "Sync Repos"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # - name: Checkout dest repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: Anefu/php-todo
      #     ssh-key: ${{ secrets.DEST_SSH_KEY }}
      #     path: ./php-todo

      - name: Create tag in source repo
        run: |
          git config user.email "test@gmail.com"
          git config user.name "praise"
          git tag -a v1.0 -m "test tag"
          git push origin v1.0

      - name: Add destination remote
        run: |
          git remote add dest https://github.com/Anefu/php-todo.git
          git fetch --tags

      - name: Push to remote repo
        run: |
          git checkout dest/main
          git merge v1.0
          git push dest main
