name: Sync Repos
on:
  push:
    branches:
      - dev

env:
  SRC_REPO: ./
  DEST_REPO: Anefu/php-todo

jobs:
  Sync:
    name: "Sync Repos"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: ./deploy-java

      - name: Checkout dest repo
        uses: actions/checkout@v3
        with:
          repository: $DEST_REPO
          ssh-key: ${{ secrets.DEST_SSH_KEY }}
          path: ./${DEST_REPO##*/}
          ref: main

      - name: Create tag in source repo
        run: |
          cd deploy-java
          export TAG=$(( $RANDOM % 10 ))
          git config user.email "test@gmail.com"
          git config user.name "praise"
          git tag -a $TAG -m "test tag"
          git push origin $TAG

      - name: Sync directories
        run: |
          cd deploy-java
          git fetch --tags
          git checkout v1.0
          rsync -av --exclude='**/.git*' --exclude='**/*.yml' ./ ../${DEST_REPO##*/}
      
      - name: Create commit and push
        run: |
          cd ./${DEST_REPO##*/}
          git checkout main
          git config user.email "test@gmail.com"
          git config user.name "praise"
          git add .
          git commit -m "test sync" || exit 0
          git push origin main
